### ISSUE TITLE
Null pointer exception when a binding refers to an undefined alias

### ISSUE THREAD

**Issue by sanhozay** [sanhozay/CLGen#5]
Parsing should report an error but not produce a stack trace.

Test case:

    item("Parking Brake") {
        state("ON", brake > 0) brake = 1;
    }
    checklist("Before Starting Engines") {
        check("Parking Brake", "ON");
    }

Stack trace:

    $ clgen test.clg
    CLGen 1.1.1
    error at line 2: Alias 'brake' is not defined in item 'Parking Brake'
        state("ON", brake > 0) brake = 1;
                    ^
    error at line 2: Alias 'brake' is not defined in item 'Parking Brake'
        state("ON", brake > 0) brake = 1;
                               ^
    java.lang.NullPointerException
            at org.flightgear.clgen.listener.ItemListener.enterAssignInt(ItemListener.java:258)
            at org.flightgear.clgen.CLGenParser$AssignIntContext.enterRule(CLGenParser.java:1445)
            at org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:42)
            at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:25)
            at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
            at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
            at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
            at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
            at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
            at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
            at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
            at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
            at org.flightgear.clgen.CLGen.buildItems(CLGen.java:170)
            at org.flightgear.clgen.CLGen.run(CLGen.java:126)
            at org.flightgear.clgen.CLGen.main(CLGen.java:80)
    Generation failed.

**Comment by sanhozay** [comment]
Fixed in 1.2.0
